# Generated by Django 5.2.4 on 2025-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='register_code',
            field=models.CharField(max_length=4, null=True, verbose_name='Код регистрации'),
        ),
    ]
