# Generated by Django 5.2.4 on 2025-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_register_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='invite_code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Инвайт-код'),
        ),
    ]
